version: "2.4"
services:
  emulator-1_bgload_1768296516:
    container_name: emulator-1_bgload_1768296516
    image: stress:latest
    cpus: 0.72
    mem_limit: 31G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 31G --timeout 0
