version: "2.4"
services:
  emulator-8_bgload_1768296524:
    container_name: emulator-8_bgload_1768296524
    image: stress:latest
    cpus: 1.8
    mem_limit: 53G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 53G --timeout 0
