version: "2.4"
services:
  emulator-5_bgload_1768216267:
    container_name: emulator-5_bgload_1768216267
    image: stress:latest
    cpus: 1.28
    mem_limit: 39G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 39G --timeout 0
