version: "2.4"
services:
  emulator-3_bgload_1768296518:
    container_name: emulator-3_bgload_1768296518
    image: stress:latest
    cpus: 0.68
    mem_limit: 43G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 43G --timeout 0
