version: "2.4"
services:
  emulator-5_bgload_1768296521:
    container_name: emulator-5_bgload_1768296521
    image: stress:latest
    cpus: 1.36
    mem_limit: 108G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 108G --timeout 0
