version: "2.4"
services:
  emulator-3_bgload_1767867455:
    container_name: emulator-3_bgload_1767867455
    image: stress:latest
    cpus: 0.5
    mem_limit: 2G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 2G --timeout 0
