version: "2.1"
volumes:
  dml_app:
    driver_opts:
      type: "nfs"
      o: "addr=222.201.187.50,ro"
      device: ":/home/qianguo/Edge-Scheduler/Controller/dml_app"
  dataset:
    driver_opts:
      type: "nfs"
      o: "addr=222.201.187.50,ro"
      device: ":/home/qianguo/Edge-Scheduler/Controller/dataset"
services:
  1_p1:
    container_name: 1_p1
    image: task1:v1.0
    working_dir: /home/qianguo/EdgeScheduler/Worker/dml_app/1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 0-4
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=1
      - NET_NODE_NAME=1_p1
      - NODE_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
      - NET_TASK_ID=1
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8001:4444"
    volumes:
      - ../dml_file:/home/qianguo/EdgeScheduler/Worker/dml_file
      - dml_app:/home/qianguo/EdgeScheduler/Worker/dml_app/:ro
      - dataset:/home/qianguo/EdgeScheduler/Worker/dataset/:ro
    command: python3 gl_peer.py
  1_n1:
    container_name: 1_n1
    image: task1:v1.0
    working_dir: /home/qianguo/EdgeScheduler/Worker/dml_app/1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 5-9
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=2
      - NET_NODE_NAME=1_n1
      - NODE_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
      - NET_TASK_ID=1
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8002:4444"
    volumes:
      - ../dml_file:/home/qianguo/EdgeScheduler/Worker/dml_file
      - dml_app:/home/qianguo/EdgeScheduler/Worker/dml_app/:ro
      - dataset:/home/qianguo/EdgeScheduler/Worker/dataset/:ro
    command: python3 gl_peer.py
  1_n2:
    container_name: 1_n2
    image: task1:v1.0
    working_dir: /home/qianguo/EdgeScheduler/Worker/dml_app/1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 10-14
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=3
      - NET_NODE_NAME=1_n2
      - NODE_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
      - NET_TASK_ID=1
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8003:4444"
    volumes:
      - ../dml_file:/home/qianguo/EdgeScheduler/Worker/dml_file
      - dml_app:/home/qianguo/EdgeScheduler/Worker/dml_app/:ro
      - dataset:/home/qianguo/EdgeScheduler/Worker/dataset/:ro
    command: python3 gl_peer.py
  1_n3:
    container_name: 1_n3
    image: task1:v1.0
    working_dir: /home/qianguo/EdgeScheduler/Worker/dml_app/1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 15-19
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=4
      - NET_NODE_NAME=1_n3
      - NODE_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
      - NET_TASK_ID=1
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8004:4444"
    volumes:
      - ../dml_file:/home/qianguo/EdgeScheduler/Worker/dml_file
      - dml_app:/home/qianguo/EdgeScheduler/Worker/dml_app/:ro
      - dataset:/home/qianguo/EdgeScheduler/Worker/dataset/:ro
    command: python3 gl_peer.py
  1_n4:
    container_name: 1_n4
    image: task1:v1.0
    working_dir: /home/qianguo/EdgeScheduler/Worker/dml_app/1
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    cpuset: 20-24
    mem_limit: 2048M
    environment:
      - EDGE_TB_ID=5
      - NET_NODE_NAME=1_n4
      - NODE_PORT=4444
      - NET_CTL_ADDRESS=222.201.187.50:3333
      - NET_AGENT_ADDRESS=222.201.187.51:3333
      - NET_TASK_ID=1
    healthcheck:
      test: curl -f http://localhost:4444/hi
    ports:
      - "8005:4444"
    volumes:
      - ../dml_file:/home/qianguo/EdgeScheduler/Worker/dml_file
      - dml_app:/home/qianguo/EdgeScheduler/Worker/dml_app/:ro
      - dataset:/home/qianguo/EdgeScheduler/Worker/dataset/:ro
    command: python3 gl_peer.py
