version: "2.4"
services:
  emulator-10_bgload_1768216272:
    container_name: emulator-10_bgload_1768216272
    image: stress:latest
    cpus: 1.92
    mem_limit: 46G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 46G --timeout 0
