version: "2.4"
services:
  emulator-4_bgload_1768216266:
    container_name: emulator-4_bgload_1768216266
    image: stress:latest
    cpus: 0.8
    mem_limit: 107G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 107G --timeout 0
