version: "2.4"
services:
  emulator-6_bgload_1768296522:
    container_name: emulator-6_bgload_1768296522
    image: stress:latest
    cpus: 1.32
    mem_limit: 110G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 110G --timeout 0
