version: "2.4"
services:
  emulator-9_bgload_1768296525:
    container_name: emulator-9_bgload_1768296525
    image: stress:latest
    cpus: 0.76
    mem_limit: 78G
    restart: unless-stopped
    command: stress-ng --cpu 1 --vm 1 --vm-bytes 78G --timeout 0
