# config.yaml
training:
  num_phys_nodes: 10
  num_virtual_tasks: [3, 5]  # 随机范围
  resource_ranges:
    cpu: [1, 16]
    ram: [1, 32]
    bandwidth: [50, 500]
  ppo_params:
    lr: 3e-4
    gamma: 0.99
    clip_epsilon: 0.2
    ppo_epochs: 4
    buffer_size: 10000
    episodes_per_update: 10